name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            exe: ""
            cc: "clang"
          - os: ubuntu-latest
            exe: ""
            cc: "clang"
          - os: ubuntu-latest
            exe: ""
            cc: "gcc"
          # - os: windows-latest
          #   exe: ".exe"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - run: sudo apt-get update
        if: runner.os == 'Linux'
      - run: sudo apt-get install -y libcurl4-openssl-dev
        if: runner.os == 'Linux'

      - run: curl -L -o curl.zip https://curl.se/windows/latest.cgi?p=win64-mingw.zip
        if: runner.os == 'Windows'
      - run: unzip curl.zip
        if: runner.os == 'Windows'
      - run: find . -name libcurl.dll.a -exec cp -v '{}' . ';'
        if: runner.os == 'Windows'

      - uses: actions/checkout@v6
      - run: ${{ matrix.cc }} -Wall -g -o build${{ matrix.exe }} build.c
      - run: ./build${{ matrix.exe }}
      - run: ./test-tool${{ matrix.exe }} 'view_local_file' '{"path":"build.c"}'

